# Generated by Django 4.0.5 on 2022-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='indextypegoodsbanner',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
    ]
