# Generated by Django 4.0.5 on 2022-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='删除标记'),
        ),
    ]
